blank_issues_enabled: false
contact_links:
  - name: ⚠️ MCT Long Term Support Notice
    url: https://github.com/TPM-Repos/ModifiedCorporateTheme#readme
    about: This project is in LTS mode. We only accept bug reports and security issues. For new features, please consider TSIT.
